#!/bin/bash

# This script generates a zscript.zs file that #includes every .zs source code
# file in this project.

echo -e "version 4.1.3

// This file is generated by scripts/make_zscript_head.sh.
// Do not edit it by hand: your changes will be overwritten.
" > zscript.zs

sources=$(find zscript -name "*.zs")
extends=$(grep -nrPzl "extend.*\\nclass" zscript | grep -v "~" | sort)
sources=$(echo "$sources" | grep -v "$extends" | sort)

includes=$(echo "$sources" | while read -r f; do echo "#include \"$f\""; done)

includes_extends=$(echo "$extends" | while read -r f; do echo "#include \"$f\""; done)

echo "$includes
// class extensions:
$includes_extends" >> zscript.zs
