#!/bin/bash

# This script generates a zscript.zs file that #includes every .zs source code
# file in this project.

echo -e "version 4.1.3

// This file is generated by scripts/make_zscript_head.sh.
// Do not edit it by hand: your changes will be overwritten.
" > zscript.zs

includes=$(find zscript -name "*.zs"| while read -r f; do echo "#include \"$f\""; done | sort -r)

echo "$includes" >> zscript.zs
