#!/bin/bash

echo -e "version 4.1.3\n\n"\
"// This file is generated by scripts/make_zscript_head.sh.\n"\
"// Do not edit it by hand: your changes will be overwritten.\n" > zscript.zs

includes=$(find zscript -name "*.zs"| while read f; do echo "#include \"$f\""; done | sort -r)

echo "$includes" >> zscript.zs
